### ISSUE TITLE
Possible conflict between directories and files with the same name

### ISSUE THREAD

**Issue by brandonweiss** [aseemk/requireDir#12]
I've got a directory structure that looks like this:

- tasks
  - test
    - local.js
    - remote.js
  - build.js
  - test.js

The output from recursively requiring is:

`{ build: {}, test: { local: {}, remote: {} } }`

But if I rename `test.js` to `foobar.js`, I get:

`{ build: {}, foobar: {}, test: { local: {}, remote: {} } }`

It would appear it can't require directories and files if they have the same.

**Comment by aseemk** [comment]
That's the default behavior by design since file extensions are stripped.

You can achieve what you want by passing `duplicates: true`. Then, you should get:

`{build: {}, 'build.js': {}, test: {local: {}, 'local.js': {}, remote: {}, 'remote.js': {}}, 'test.js': {}}`

**Comment by aseemk** [comment]
Hope that helps; feel free to re-open if it doesn't!
