### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by simon-p-r** [aseemk/requireDir#14]
Hi

Is there no option to filter out directories you don't want to require?  Folders such as .git or node_modules are 2 directories you may want to filter from a directory require.

**Comment by sholladay** [comment]
There doesn't seem to be an option for that, but luckily both of your example cases should be handled already. `require-dir` actively [ignores](https://github.com/aseemk/requireDir/blob/0.3.0/index.js#L72) `node_modules`. And the strategy it uses for determining basenames (removes extensions), should lead to an empty string for anything starting with `.`, which hopefully wouldn't get required or end up in the result list, but I haven't tested that.

**Comment by cxoltero** [comment]
I guess you could do something like this:
.src(['!./src/js/**/*.test.js', './src/js/**/*.js'])

you just tell the array not to take the test files in this case. in your case would be something like:

.src["!./.git", "!./node_modules"]

**Comment by contra** [comment]
done, will be published in next npm release

**Comment by sunnixx** [comment]
Hi anything on this ?

**Comment by yocontra** [comment]
@sunnixx This has been published already, see the README https://github.com/aseemk/requireDir#options
