### ISSUE TITLE
Can't import file and folder with the same name

### ISSUE THREAD

**Issue by kdela** [aseemk/requireDir#16]
Hi. I just tried import files from folder recursively, and unfortunately my folders have name conflict with another files.

├── build
│   ├── clean.js
├── build.js
├── default.js
├── dev
│   ├── browserSync.js
└── dev.js

With this example files 'build.js' and 'dev.js' wont be loaded.

**Comment by aseemk** [comment]
It should work with `duplicates: true` (along with `recurse: true` still).

Feel free to re-open if it doesn't.

**Comment by kdela** [comment]
I wondering why It's not a default behaviour. Anyway, It's obviously working now, thank you @aseemk!

**Comment by aseemk** [comment]
To mimic Node's native `require`: if you have a `build` directory alongside `build.js`, `require('./build')` will require the directory, not the file. =)
