### ISSUE TITLE
Error: Cannot find module 'require‐dir'

### ISSUE THREAD

**Issue by leanne1** [aseemk/requireDir#19]
I know this has been raised before but i don't see the solution. 

```
npm install require-dir --save-dev
```

Package gets installed.

In gulpfile: 

```
var requireDir = require('require‐dir');
requireDir('./folder-a/folder-b');
```

Error message:

```
module.js:338
    throw err;
    ^
Error: Cannot find module 'require‐dir'
etc ...
```

Node v0.12.7

Could you please explain why I am getting this error and if there is a simple fix?

Thanks

**Comment by drouillard** [comment]
you try with just --save instead of --save-dev?

**Comment by aseemk** [comment]
This is a good q. We recently upgraded to Node 0.12 and I've started seeing this too!

I don't know what's causing this yet — I've already tried to rework the code to see if I can overcome it, unsuccessfully — but one workaround for now is to `npm uninstall require-dir` and then undo that.

Sorry about that! I hope to figure out the issue sometime...

**Comment by lee-40square** [comment]
Well, with Node 4.0 I wonder how this issue will work out. At least we're going to get some stable release cycles. :-)

**Comment by Kratos-SA** [comment]
+1

**Comment by contra** [comment]
Shouldn't be an issue anymore, closing.
