### ISSUE TITLE
Support .es6 extensions

### ISSUE THREAD

**Issue by mikeerickson** [aseemk/requireDir#30]
Is there an easy way to support .es6 files, or should just modify require-dir source to allow it?

**Comment by aseemk** [comment]
It already supports it, as long as you've registered `.es6` normally. =)

Two ways to do that:

- If you want to use Node's native ES6 support:

  ```js
  require.extensions['.es6'] = require.extensions['.js'];
  requireDir('...');
  ```

- If you want to use Babel, etc., `require('babel/register')` or w/e before `requireDir`.

Hope this helps!

**Comment by aseemk** [comment]
Please feel free to re-open if I didn't answer your q!

**Comment by mikeerickson** [comment]
Perfect, that's what I have been searching for (figured it was something like that but didn't know exactly what search for on Google) 

Thx!
