### ISSUE TITLE
If a directory and a file have the same basename only one gets processed

### ISSUE THREAD

**Issue by fabiospampinato** [aseemk/requireDir#32]
Take a look at Semantic-UI's [tasks folder](https://github.com/Semantic-Org/Semantic-UI/tree/master/tasks): they have a `build.js` main task, that requires all the individual partial builders from the `build` directory, both are located at the same path.

I'm building something similar, but in a cleaner why with the help of this library. The problem is that since both objects have the same basename only the directory gets processed, hence the `build.js` file never gets loaded.

A possibile solution to this problem would be to overwrite the previously defined key of the returned hash, I think that processing all the files is more important. In my case none of the files located in the `build` directory is even actually exporting anything.

**Comment by bondden** [comment]
Have you tried setting `duplicates` option to `true` as it's described in [Readme](https://github.com/aseemk/requireDir#options)?

**Comment by fabiospampinato** [comment]
Setting `duplicates` to `true` works. I must have missed it, thanks!
