### ISSUE TITLE
with require do I need gulp required on all tasks files?

### ISSUE THREAD

**Issue by Riskbreaker01** [aseemk/requireDir#35]
all my require requireDir('path/dir') need this in their files:

var gulp = require('gulp');

Is there a way that  require('gulp') only has the need to set this in the gulpfile.js and not on every individual files in the path?...I feel like there should be a way not to have to add these to all the files that are added but have to in this case. It seems to make process delay.

**Comment by aseemk** [comment]
There isn't any way today.

It's unlikely this is delaying your process. Node caches `require`s, so Gulp is only really getting `require`d once under the hood.

You could confirm this by adding `console.time` and `console.timeEnd` calls before the `require`s.

**Comment by Riskbreaker01** [comment]
I guess that makes sense ...maybe i just didn't want to add that repeated on every task pages, but if it has to be done than so be it

**Comment by aseemk** [comment]
I hear you. =) The more I think about this issue btw, the more it feels like it'd be a great feature for _Gulp_ to have (being able to automatically require a file in every task). Mocha has this (`--require`):

http://mochajs.org/#usage

So I encourage you to ask on a Gulp mailing list, etc. Good luck!
