### ISSUE TITLE
Reading tasks from parent directories?

### ISSUE THREAD

**Issue by stevenleija** [aseemk/requireDir#44]
Is it not possible to read gulp task files from a parent directory? I have the following directory structure and using

require('require-dir')('../../config/gulp/tasks');

Doesn't read in the files.  But if I copy the folder gulp/tasks into my Modules A directory and update the paths then it works perfectly.  I'm trying to prevent unncessary duplicate task files.

- project root
  - config
    - gulp
      -tasks
- modules
  - module A
  - module B

Thank you for any help.

**Comment by stevelacy** [comment]
What OS/node version?

I did a simple test and it seems that `requireDir('../../')` does resolve correctly
