### ISSUE TITLE
Crash on Node 8

### ISSUE THREAD

**Issue by trongthanh** [aseemk/requireDir#50]
I got this error when running a project using it in Node 8

```
[...]/server/node_modules/require-dir/index.js:97
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^
TypeError: require.extensions.hasOwnProperty is not a function
```

It seems that `require.extensions` is [deprecated and removed](https://nodejs.org/api/globals.html#globals_require_extensions) from Node 8. Any plan to upgrade this package for newer Node?

**Comment by stevelacy** [comment]
did you update to the latest? #45

**Comment by trongthanh** [comment]
False alarm. Thought I got the latest version of it. Sorry. 😋
