### ISSUE TITLE
Adding to CITGM

### ISSUE THREAD

**Issue by benjamingr** [aseemk/requireDir#51]
Hey,

We'd like to add `require-dir` to Node.js's Canary In The Gold Mine. ([currently tested packages](https://github.com/nodejs/citgm/blob/master/lib/lookup.json))

This means new releases of Node will run `require-dir`'s unit tests as integration tests and should prevent issues like https://github.com/aseemk/requireDir/issues/45 from happening in the future. 

It would have let us catch the issue back at https://github.com/nodejs/node/pull/10789

In order for us to do that - we need @aseemk (or another maintainer) to agree to be reachable and responsive for problems (as they may influence Node version releases directly).

@aseemk what do you say? Would you be up for it? It would have certainly saved me time personally if `require-dir` was there :)

**Comment by aseemk** [comment]
Very cool to hear! Thanks for the offer.

I can try, but @stevelacy, will you be able to help too?

**Comment by stevelacy** [comment]
I can assist

**Comment by contra** [comment]
Is there anything left to be done for this?

**Comment by contra** [comment]
Closing since I didn't get a response
