### ISSUE TITLE
Relative requires broken in Jest tests

### ISSUE THREAD

**Issue by nickmccurdy** [aseemk/requireDir#53]
Please refer to https://github.com/facebook/jest/issues/4567.

It appears that a Jest specific issue causes `require-dir`'s module resolution to happen relatively to the test package instead of the parent package. This causes dependents of `require-dir`, including `npm-check-updates`, to break when used in Jest tests.

**Comment by nickmccurdy** [comment]
It seems like prefixing relative path arguments with `__dirname` fixes this. Is there a way we could do this within `require-dir` in a way that still works in Jest?

**Comment by nickmccurdy** [comment]
Nevermind, that doesn't fix it, Jest's environment incorrectly returns empty directory contents (which breaks this library) because Jest doesn't support `module.parent`, which this library relies on.

Unfortunately this means that `require-dir` can't be used in Jest (even by an indirect dependency) unless the issue is fixed upstream. For now I'd recommend that projects using Jest migrate away from this library using a static `index.js` file of imports and exports instead.

**Comment by nickmccurdy** [comment]
Fixed by https://github.com/facebook/jest/pull/4614.

**Comment by Elliot128** [comment]
Still seeing this in jest 22.1.4.

**Comment by Maxobat** [comment]
This is still happening for me with Jest 22.4.2.

**Comment by SokratisVidros** [comment]
Same for me, Jest 22.4.2

**Comment by contra** [comment]
Yeah, this is a jest bug. Nothing we can really do from this library - sorry! Open a ticket on the jest repo for it - this also might be related https://github.com/facebook/jest/issues/5235

**Comment by SokratisVidros** [comment]
Currently the problem with Jest lies in https://github.com/aseemk/requireDir/blob/master/index.js#L98. In Jest land `require.extensions` is an empty object `{}`. That way, `map` variable is not populated correctly. Please note that `require.extensions` is also deprecated in latest node.

I've tried various, hacky solutions via Jest preprocessors as stated in [this related issue](https://github.com/facebook/jest/issues/281) but they didn't work.

I am sorry but I have to switch to `require-directory` package that doesn't have the `require.extensions` dependency. I really hope the above information help into addressing the problem faster.
